### ISSUE TITLE
 such file or directory: 'ckpt/FreDSNet_weights.pth

### ISSUE THREAD

**Issue by samikhan66** [Sbrunoberenguel/FreDSNet#3]
Traceback (most recent call last):
  File "inference.py", line 65, in <module>
    net,state_dict = model.load_weigths(args)
  File "C:\Users\sami_\FreDSNet\FreDSNet_model.py", line 395, in load_weigths
    state_dict = torch.load(args.pth,map_location='cpu')
  File "C:\Users\sami_\anaconda3\envs\FreDS\lib\site-packages\torch\serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\sami_\anaconda3\envs\FreDS\lib\site-packages\torch\serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\sami_\anaconda3\envs\FreDS\lib\site-packages\torch\serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'ckpt/FreDSNet_weights.pth'

**Comment by Sbrunoberenguel** [comment]
Hello,

this issue is addressed and solved in [here](https://github.com/Sbrunoberenguel/FreDSNet/issues/1)

I'll try to update it ASAP
